### ISSUE TITLE
Record vendor branches as merge commits, not cherry-picks

### ISSUE THREAD

**Issue by uqs** [freebsd/git_conv#1]
... even though their tree's are quite different

**Comment by emaste** [comment]
Reference: https://lists.freebsd.org/pipermail/freebsd-git/2020-March/000239.html

**Comment by emaste** [comment]
Note that some updates are indeed recorded as merges (with independent trees), e.g. https://github.com/freebsd/freebsd/commit/ca8624403626d5a4e13f5006026ca6ba40c12ac5

**Comment by uqs** [comment]
Weird, that shouldn't have happened with the way the old conversion is done.

There was a time though, when an unpatched svn2git was in effect, which would've recorded everything as merges. We'll never know. As long as the new repo does the right thing ...

**Comment by emaste** [comment]
I think this is still not working - I updated and rebuilt svn2git and reran the conversion, and the [commit Warner reported](https://lists.freebsd.org/pipermail/freebsd-git/2020-March/000239.html) is still not recorded as a merge commit. I haven't re-fetched from etoilebsd though, could you check this commit in your conversion?

**Comment by uqs** [comment]
https://svnweb.freebsd.org/base?view=revision&revision=337810 does not copy any files, hence it's not recorded as a git merge. I don't think svn2git uses "mergeinfo" for anything.

We have quite a number of potential candidates for this. You can try to see "all" MFV and their parents like so, indicating whether it was a merge or not:

% git log --pretty=format:'%h %p' --grep="^MFV"|head
7185e224e801 08784068221f
30cb5f87d58c 1b93be5eb3c2
03b142b191e9 e752562d45e8
cbddfb51e1c0 03d3005e2375
11fb98714768 378cd0c648ca 68213bdd9cb8
8a006eaa8006 259704405104 65da968c5ce7
70f196ad78cc 7918a9ea0e6b
bcf0316a07fd 77522e72bd10 8185c4ae244f
072786e78a1f 64ed92811c79 17574e7f034b
b53e3730d61d 520900eb3be8
...

We seem to have more normal commits than merge commits for those.

Commit 11fb98714768 is a proper one, as you can also see from its SVNweb page:
https://svnweb.freebsd.org/base?view=revision&revision=358652

**Comment by uqs** [comment]
I think we have 2 options:
1. live with it
2. do manual fixups post-conversion, i.e. record these, find out their potential "other" parent and then rewrite the commits as such.

Can someone write a script that goes over the SVN data and extracts all merges? Like 
rev123 was a merge from branch foo@122 into bar or somesuch. Then we could probably string the pieces together.

**Comment by uqs** [comment]
I've added some debug statements to the converter, and the first rev that has some mergeinfo attached is https://svnweb.freebsd.org/base?view=revision&revision=179468, which is fine.

The rev under question however does *NOT* have a mergeinfo as per the exposed fields in the API. I guess we need an SVN expert to explain this mergeinfo to us. I think the problem is that the converter is walking several svn_fs_path_change2_t items, but maybe not the one that has the proper mergeinfo attached?

`svn log -vc 337810` does not say anything about a mergeinfo. `svn diff -c 337810` does produce the required output though.

**Comment by uqs** [comment]
This is basically done. Most of the SVN merges from vendor are being recorded as git merges.
