### ISSUE TITLE
Examine ability to connect the repository with history of historic Unix releases

### ISSUE THREAD

**Issue by dspinellis** [freebsd/git_conv#10]
Being able to run `git blame` and `git log` back to historic (e.g. pre-FreeFBSD 1.0) releases can be useful. However, directly including such releases in the repo is problematic:
* A lot of old information is available as snapshots or file-level commits rather than as atomic commits
* Uncertainty on how snapshots are to be interpreted (e.g. with regard to authors) means that
  the historic releases can change as their interpretation becomes more accurate, affecting the
  SHAs of newer commits
* The usefulness of having access to past revisions decreases as these become older

Using `git replace` it might be able to link historic releases (e.g. through the [Unix history repository](https://github.com/dspinellis/unix-history-repo)) without affecting the main repository's stability and integrity.

**Comment by uqs** [comment]
wontfix
