### ISSUE TITLE
Add conversion / upload cron script to git_conv repo

### ISSUE THREAD

**Issue by emaste** [freebsd/git_conv#19]
Discussed on the 2020-07-07 call, let's add to this repo the script to run the conversion and push the results. Came up during discussion of the `git gc --aggressive`.

**Comment by uqs** [comment]
Note that the gc run cannot be easily done inline, as that repo is owned by a different user currently.

**Comment by uqs** [comment]
Turns out updating the authors file isn't as trivial as I had hoped, as the jail where the converter runs doesn't see all the accounts with `getent passwd`, so we would have to get this data from freefall or similar somehow ...
