### ISSUE TITLE
convert the history of the access file

### ISSUE THREAD

**Issue by uqs** [freebsd/git_conv#21]
should also try to get the history of cvs-access,v in addition to svnadmin/conf/access

push to an orphaned branch

**Comment by uqs** [comment]
@lwhsu the next run should produce and push an `admin` branch for all three repos with the access and mentors files. What else do we need?

**Comment by lwhsu** [comment]
@uqs thanks, I'll check when it gets published.  After check, these files are being used in the doc/svnadmin/conf:

access
approvers
mentors
paths
sizelimit.conf

I am not sure the history of the files other than access and mentors are worth to keep or not, let's discuss in the next meeting.

BTW, there are some more in ports and src's svnadmin, but I'll focus on doc repository first.

**Comment by uqs** [comment]
Looks like I cannot use the name refs/admin, see

```
remote: error: refusing to create funny ref 'refs/admin' remotely  
```

I'm not sure yet if git allows "arbitrary" refs like refs/vendor/foo but not refs/vendor, for example.

Ah yes indeed: https://sourcegraph.com/github.com/git/git/-/blob/refs.c#L205

So, what shall we name this ref? If we're going with refs/heads/admin, then the 'admin' branch will be visible to everyone in `git branch -a` output, something I'd like to avoid. Maybe refs/internal/admin instead?

**Comment by lwhsu** [comment]
Sorry for late reply.  I don't have strong opinion of this.  IMHO, having the access and mentors files publicly visible isn't a bad thing because it shows a meaningful history so I'm also fine with `refs/heads/admin`.

**Comment by bsdimp** [comment]
For administrative files, we can push a new series of hashes with proper dates/user names at the end of the branch to avoid hash changes, should we need to make tweaks in the future.

**Comment by uqs** [comment]
Everything is public, really :) it's more about whether we want it to eternally clutter up peoples' terminal output, or not. I've stuck with `internal/admin` for now and fixed some tiny snafus in the commit messages.

See
https://cgit-beta.freebsd.org/src/log/?h=internal/admin
https://cgit-beta.freebsd.org/doc/log/?h=internal/admin
https://cgit-beta.freebsd.org/ports/log/?h=internal/admin

The converter now also runs faster and I've increased cadence to 5x per day for each repo.

**Comment by lwhsu** [comment]
> Everything is public, really :) it's more about whether we want it to eternally clutter up peoples' terminal output, or not. I've stuck with `internal/admin` for now and fixed some tiny snafus in the commit messages.

Yeah I'm also fine with this. I should have used the words "public visible by default" or something else, but you know how it works. What I meant was it's also nice to advertise it because those are "honor" histories.

**Comment by uqs** [comment]
Now that you mention it, I forgot to document it, oops.
