### ISSUE TITLE
teach cgit to handle tags better

### ISSUE THREAD

**Issue by uqs** [freebsd/git_conv#24]
The problem is that it prepends refs/tags/ to a tag ref unconditionally, so going from
https://cgit-beta.freebsd.org/src/log/?h=refs/vendor/xz/dist
to
https://cgit-beta.freebsd.org/src/tag/?h=refs/vendor/xz/5.2.5
results in a "bad tag reference"

The problematic code is here: https://sourcegraph.com/github.com/zx2c4/cgit@adcc4f822fe11836e5f942fc1ae0f00db4eb8d5f/-/blob/ui-tag.c#L50-54
and from the looks it just needs a conditional to leave the tag alone, if it starts with "refs/" already.

Will need to find out how to submit a patch to cgit over the holidays ...

@lwhsu FYI only.

**Comment by lwhsu** [comment]
cc @delphij

**Comment by uqs** [comment]
this is no longer important, as we changed the location of the vendor tags refs
