### ISSUE TITLE
git hooks

### ISSUE THREAD

**Issue by uqs** [freebsd/git_conv#4]
What sort of hooks do we need installed?

-  disallowing merge commits?
-  how to prevent people from faking the committer string to something else?
- enforce that committer uses @FreeBSD.org address?
- ?

**Comment by emaste** [comment]
- disallowing merge commits, with some exceptions
  - only certain users can push merge commits (similar to how we handle large commits today)
  - only certain paths can receive merge commits (e.g., only _contrib/_)
  - a combination of the above
- committer string must be @FreeBSD.org, at least initially
  - committer string matches ssh key?
- preventing commits to certain branches, absent an "approved by" tag?
  - start with master branch commits only?

**Comment by emaste** [comment]
@bapt pointed out that these restrictions can be implemented via gitolite config

**Comment by lwhsu** [comment]
We're importing  useful hooks from:
https://svnweb.freebsd.org/base/svnadmin/hooks/
https://svnweb.freebsd.org/doc/svnadmin/hooks/
https://svnweb.freebsd.org/ports/svnadmin/hooks/
