### ISSUE TITLE
Fix $Id$ tags to match the actual CVS revision

### ISSUE THREAD

**Issue by uqs** [freebsd/git_conv#7]
Basically infeasible, but currently SVN has the $Id$ off-by-one, meaning the $Id$ tag being committed in revision N is actually the content of N-1. It would be sweet to fix this up, otherwise future archaeologists will scratch their heads.

Example in ports:

```
% git log -p -- databases/db/Makefile
...
commit 6dca55ed122f25b1bbe40274341eac760a75bdba
Author: James FitzGibbon <jfitz@FreeBSD.org>
Date:   1997-09-05 20:22:12 +0000

    Upgrade to v2.2.6
    Submitted by:   Josh Tiefenbach <josh@ican.net>

Notes:
    svn path=/head/; revision=7783

diff --git a/databases/db/Makefile b/databases/db/Makefile
index 1d11be7da943..c8764c99ac7d 100644
--- a/databases/db/Makefile
+++ b/databases/db/Makefile
@@ -1,12 +1,12 @@
 # ports collection makefile for:       Berkeley DB
-# Version required:                    v2.1.0
+# Version required:                    v2.2.6
 # Date created:                                12 Jun 1997
 # Whom:                                        Josh Tiefenbach <josh@ican.net>
 #
-# $Id:$
+# $Id: Makefile,v 1.1.1.1 1997/06/13 17:54:36 jfitz Exp $
 #
...
commit 1f93dcfb8c1e47b7259ce47c4e1216856405eb92
Author: James FitzGibbon <jfitz@FreeBSD.org>
Date:   1997-06-13 17:54:36 +0000

    Import of Berkely DB 2.0
    Submitted by:   Josh Tiefenbach <josh@ican.net>

Notes:
    svn path=/head/; revision=6913

diff --git a/databases/db/Makefile b/databases/db/Makefile
new file mode 100644
index 000000000000..1d11be7da943
--- /dev/null
+++ b/databases/db/Makefile
@@ -0,0 +1,27 @@
+# ports collection makefile for:       Berkeley DB
+# Version required:                    v2.1.0
+# Date created:                                12 Jun 1997
+# Whom:                                        Josh Tiefenbach <josh@ican.net>
+#
+# $Id:$
...
```

Note how the initial commit has an empty Id, and the second commit has the Id date of the first commit.

I have no idea whether this expansion was done by cvs2svn, or whether it is purely a byproduct of the working tree at the time of the CVS commit.

There should be a simple heuristic to take all the diffs to Ids, check their previous commit for its date/time and if there's a match, hoist it over.

Who's going to write that script though?

**Comment by emaste** [comment]
The same issue affects CVS `$FreeBSD$` tags too I suppose?

Did CVS just record in the ,v file the content as submitted, expanding/replacing `$FreeBSD$` or `$Id$` on checkout/update?

**Comment by uqs** [comment]
Man, it's been some time, but yes, I think CVS only expanded on checkout and did *not* un-expand during checkin. So the checked \_in\_ diff would always be bogus and the check_out_ would fix up the Id to be whatever it needs to be.

I don't feel strongly about this. Should there be someone in the project that really wants to fix this up for whatever reason, *now* would be the time to get started on this.

**Comment by uqs** [comment]
For src, we will bring back the CVS IDs for the release tags (only!) by shoving the checked-out code on the release ISO images back into git.

Whether these commits and tags are to replace the regular release tags or have new names is tbd (currently they are called 4.3.0_shipped)

**Comment by uqs** [comment]
Obsoleted in favor of issue #8
